flags: {}
packages:
- '.'
- 'netlist/verilog'
- 'netlist/netlist-to-verilog'
- 'netlist/netlist-to-vhdl'
- 'netlist/netlist'
- location:
    git: git@github.com:conal/circat
    commit: ec2d1b3aa9adeb91bb91e9a890011eeb14ea4c82
extra-deps:
- applicative-numbers-0.1.3
- treeviz-2.0.3
- ty-0.1.6
- type-unary-0.2.21
resolver: lts-2.22
